
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Starting backfill for Chat Rooms...");

  try {
    const courses = await prisma.khoaHoc.findMany({
      include: {
        phongChat: true,
      },
    });

    console.log(`Found ${courses.length} courses.`);

    let createdCount = 0;

    for (const course of courses) {
      if (!course.phongChat) {
        console.log(`Creating chat room for course: ${course.tenKhoaHoc} (${course.id})`);
        try {
          // Explicitly creating maMoi if default doesn't trigger in some prisma versions (unlikely but safe)
          // But rely on default first.
          await prisma.phongChat.create({
            data: {
              tenPhong: course.tenKhoaHoc,
              khoaHocId: course.id,
              // maMoi will be generated by @default(uuid())
              // id will be generated by @default(uuid())
            },
          });
          createdCount++;
        } catch (error) {
          console.error(`Failed to create chat room for course ${course.id}:`, error);
        }
      } else {
         // console.log(`Chat room already exists for course: ${course.tenKhoaHoc}`);
      }
    }

    console.log(`Backfill complete. Created ${createdCount} chat rooms.`);
  } catch (err) {
    console.error("Error connecting to database or fetching courses:", err);
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
